#define CREATE_ERR 2
#define READ_ERR 3
#define WRITE_ERR 4
#define MARKER_ERR 5
#define CLOSE_ERR 6
#define SIZE_ERR 7
#define MAX_FOPENED_ERR 8
#define NOTEXIST_ERR 9
#define BADDESC_ERR 10
#define EXIST_ERR 11
#define MAXFILES_ERR 12
#define EOF_ERR 13
#define OPEN_ERR 14
#define END_ID -15